apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: simple-push-main
  annotations:
    # pipelinesascode.tekton.dev/on-comment: "^/(help|(assign|unassign|label|unlabel)[ ].*)"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && target_branch == "main"
spec:
  params:
    - name: url
      value: 'image-registry.openshift-image-registry.svc:5000/{{target_namespace}}/httpd:{{tag}}'
  pipelineSpec:
    tasks:
      - name: task
        displayName: This is a task test
        taskSpec:
          steps:
            - name: task-step
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "$(params.url)"
                exit 0  
